### PR TITLE
prefix_sum，two_pointer and relabel

### PR DESCRIPTION
**Pull request by Xavier2323**

### CODE REVIEW

**Comment by harry900831** [comment]
you should put these chapter under fundamental section

**Comment by harry900831** [comment]
You should raise another PR for SCC

**Comment by Xavier2323** [comment]
I have raised another PR, while there is a conflict with the summary.md
change

**Comment by harry900831** [comment]
I will close this PR right now.
If you are still willing to add prefix_sum, two_pointer and relabel, please open a proposal issue and a PR for each topic respectively.

**Pull request closed without merging**
